ALTER USER 'root'@'localhost' IDENTIFIED BY 'Db2@dm1n2022';

ALTER USER 'root'@'localhost' IDENTIFIED BY 'Db2@dm1n2022' PASSWORD EXPIRE NEVER;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'Db2@dm1n2022' PASSWORD EXPIRE INTERVAL 60 DAY;
